export { ChangeDetectorRef, ChangeDetectionStrategy, inject, Component } from '@angular/core';
export { CommonModule } from '@angular/common';
export { RouterModule, ActivatedRoute } from '@angular/router';
export { FormBuilder, Validators, ReactiveFormsModule, FormsModule } from '@angular/forms';
export { Subject, Observable, of } from 'rxjs';
export { takeUntil, finalize, delay, tap, catchError } from 'rxjs/operators';
export { LocalizationService } from '../services/localization.service';
export { PublicDataService } from '../services/public-data.service';
export { LoadingService } from '../../core/services/loading.service';
export type { OnInit, OnDestroy, OnChanges, SimpleChanges } from '@angular/core';
export type { FormGroup } from '@angular/forms';
export type { HttpErrorResponse } from '@angular/common/http';