<?php

/**
 * @file ResetPasswordRequest.php
 * @path app/Http/Requests/Auth/ResetPasswordRequest.php
 * @project RPSW Web
 * @author RPSW
 * @created 2026
 * @description Input validation for completing a password reset (step 5) - token + new password.
 *
 * @refactor-note (2026-08) `Password::min(10)->mixedCase()->numbers()` replaced with the
 * policy shared across the app: `min(8)` + `max:16` + `letters()` (no mixedCase) +
 * `numbers()` + `symbols()`.
 * @refactor-note (2026-10-01) Hardening + FE parity:
 * - `password` gets an explicit `string` rule (array/object payloads are rejected cleanly
 *   instead of reaching the Password rule).
 * - `token` is format-checked (exactly 64 ASCII alphanumerics = output of Str::random(64))
 *   so oversized/garbage input is rejected before hashing and the DB lookup.
 * - Token format errors return the same generic "invalid link" text as an unknown token,
 *   so the response doesn't reveal which check failed.
 * - Policy is mirrored 1:1 on the frontend in `src/app/shared/utils/password-validation.ts`
 *   (same Unicode classes as letters()/numbers()/symbols(); length counted like mb_strlen).
 *   The two MUST be changed together.
 */

namespace App\Http\Requests\Auth;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rules\Password;

/**
 * @description FormRequest for POST /reset-password. Runs before
 *              PasswordResetController::resetPassword(), which then verifies the token
 *              against the database (hash, expiry, single use) - this class only checks shape.
 * @note Laravel returns 422 with `{ message, errors: { field: [...] } }` on failure; the
 *       frontend shows the first field error (ResetPasswordComponent::extractErrorMessage).
 */
class ResetPasswordRequest extends FormRequest
{
    /** Minimum password length - keep in sync with PASSWORD_MIN_LENGTH on the frontend. */
    private const PASSWORD_MIN = 8;

    /** Maximum password length - keep in sync with PASSWORD_MAX_LENGTH on the frontend. */
    private const PASSWORD_MAX = 16;

    /** Raw token length generated by PasswordResetController (Str::random(64)). */
    private const TOKEN_LENGTH = 64;

    /** Generic message for any token problem - identical to the controller's 400 response. */
    private const INVALID_LINK = 'The password reset link is invalid or has expired. Please request a new one.';

    /**
     * @description Public endpoint - possession of a valid token is the authorisation,
     *              and that is checked in the controller.
     * @return bool Always true.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * @description Validation rules. `max:16` uses mb_strlen for strings, matching the
     *              frontend's code-point count.
     * @return array<string, array<int, mixed>>
     */
    public function rules(): array
    {
        return [
            'token' => [
                'required', 'string', 'size:' . self::TOKEN_LENGTH, 'alpha_num:ascii',
            ],
            'password' => [
                'required', 'string', 'confirmed', 'max:' . self::PASSWORD_MAX,
                Password::min(self::PASSWORD_MIN)->letters()->numbers()->symbols(),
            ],
            'password_confirmation' => ['required', 'string'],
        ];
    }

    /**
     * @description Custom messages. All token errors collapse into one generic message
     *              (no hint whether the format or the value was wrong).
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'token.required'                 => self::INVALID_LINK,
            'token.string'                   => self::INVALID_LINK,
            'token.size'                     => self::INVALID_LINK,
            'token.alpha_num'                => self::INVALID_LINK,
            'password.confirmed'             => 'The entered passwords do not match.',
            'password.max'                   => 'The password can have a maximum of ' . self::PASSWORD_MAX . ' characters.',
            'password_confirmation.required' => 'Please confirm your new password.',
        ];
    }
}